export class AuthoritiesDemandeProduction {

    static DEMANDE_PRODUCTION_LIST_VALUE: string = "DEMANDE_PRODUCTION";
    static DEMANDE_PRODUCTION_VALUE: string = "DEMANDE_PRODUCTION";
    static DEMANDE_PRODUCTION_ADD_VALUE: string = "DEMANDE_PRODUCTION";
    static DEMANDE_PRODUCTION_UPDATE_VALUE: string = "DEMANDE_PRODUCTION";
    static DEMANDE_PRODUCTION_DELETE_VALUE: string = "DEMANDE_PRODUCTION";

}