export class AuthoritiesHistoriqueCommande {

    static HISTORIQUE_COMMANDE_LIST_VALUE: string = "HISTORIQUE_COMMANDE";
    static HISTORIQUE_COMMANDE_VALUE: string = "HISTORIQUE_COMMANDE";
    static HISTORIQUE_COMMANDE_ADD_VALUE: string = "HISTORIQUE_COMMANDE";
    static HISTORIQUE_COMMANDE_UPDATE_VALUE: string = "HISTORIQUE_COMMANDE";
    static HISTORIQUE_COMMANDE_DELETE_VALUE: string = "HISTORIQUE_COMMANDE";

}