export class AuthoritiesDemandePrixClient {

    static DEMANDE_PRIX_CLIENT_LIST_VALUE: string ="DEMANDE_PRIX_CLIENT";
    static DEMANDE_PRIX_CLIENT_VALUE: string ="DEMANDE_PRIX_CLIENT";
    static DEMANDE_PRIX_CLIENT_ADD_VALUE: string = "DEMANDE_PRIX_CLIENT";
    static DEMANDE_PRIX_CLIENT_UPDATE_VALUE: string= "DEMANDE_PRIX_CLIENT";
    static DEMANDE_PRIX_CLIENT_DELETE_VALUE: string = "DEMANDE_PRIX_CLIENT";

}