export class AuthoritiesCoordonneesBancaire{
   static  COORDOONEES_BANCAIRE_LIST_VALUE: string = "COORDOONEES_BANCAIRE";
	 static  COORDOONEES_BANCAIRE_VALUE: string = "COORDOONEES_BANCAIRE";
	 static  COORDOONEES_BANCAIRE_ADD_VALUE: string = "COORDOONEES_BANCAIRE";
	 static  COORDOONEES_BANCAIRE_UPDATE_VALUE: string = "COORDOONEES_BANCAIRE";
	 static COORDOONEES_BANCAIRE_DELETE_VALUE : string = "COORDOONEES_BANCAIRE";
}