export class AuthoritiesDeclarationEmployeur {
    static DECLARATION_EMPLOYEUR_LIST_VALUE: string = "DECLARATION_EMPLOYEUR";
    static DECLARATION_EMPLOYEUR_VALUE: string = "DECLARATION_EMPLOYEUR";
    static DECLARATION_EMPLOYEUR_EXCEL_VALUE: string = "DECLARATION_EMPLOYEUR";
    static DECLARATION_EMPLOYEUR_ADD_VALUE: string = "DECLARATION_EMPLOYEUR";
    static DECLARATION_EMPLOYEUR_UPDATE_VALUE: string = "DECLARATION_EMPLOYEUR";
    static DECLARATION_EMPLOYEUR_DELETE_VALUE: string = "DECLARATION_EMPLOYEUR";
}