export class AuthoritiesDeductionLogement {
    static DEDUCTION_LOGEMENT_LIST_VALUE: string = "DEDUCTION_LOGEMENT";
    static DEDUCTION_LOGEMENT_VALUE: string = "DEDUCTION_LOGEMENT";
    static DEDUCTION_LOGEMENT_ADD_VALUE: string = "DEDUCTION_LOGEMENT";
    static DEDUCTION_LOGEMENT_UPDATE_VALUE: string = "DEDUCTION_LOGEMENT";
    static DEDUCTION_LOGEMENT_DELETE_VALUE: string = "DEDUCTION_LOGEMENT";
}