export class AuthoritiesConditionnementEmballage {

    static CONDITIONNEMENT_EMBALLAGE_LIST_VALUE: string = "CONDITIONNEMENT_EMBALLAGE";
    static CONDITIONNEMENT_EMBALLAGE_VALUE: string = "CONDITIONNEMENT_EMBALLAGE";
    static CONDITIONNEMENT_EMBALLAGE_ADD_VALUE: string = "CONDITIONNEMENT_EMBALLAGE";
    static CONDITIONNEMENT_EMBALLAGE_UPDATE_VALUE: string = "CONDITIONNEMENT_EMBALLAGE";
    static CONDITIONNEMENT_EMBALLAGE_DELETE_VALUE: string = "CONDITIONNEMENT_EMBALLAGE";

}