export class AuthoritiesAdresseDeLivraison{

    static ADRESSE_DE_LIVRAISON_LIST_VALUE: string = "ADRESSE_DE_LIVRAISON"
    static ADRESSE_DE_LIVRAISON_VALUE: string = "ADRESSE_DE_LIVRAISON";
    static ADRESSE_DE_LIVRAISON_ADD_VALUE: string = "ADRESSE_DE_LIVRAISON";
    static ADRESSE_DE_LIVRAISON_UPDATE_VALUE: string =  "ADRESSE_DE_LIVRAISON";
    static ADRESSE_DE_LIVRAISON_DELETE_VALUE: string = "ADRESSE_DE_LIVRAISON";

}