export class AuthoritiesConditionsPaiement {

    static CONDITIONS_DE_PAIEMENTS_LIST_VALUE: string = "CONDITIONS_DE_PAIEMENTS";
    static CONDITIONS_DE_PAIEMENTS_VALUE: string = "CONDITIONS_DE_PAIEMENTS";
    static CONDITIONS_DE_PAIEMENTS_ADD_VALUE: string = "CONDITIONS_DE_PAIEMENTS";
    static CONDITIONS_DE_PAIEMENTS_UPDATE_VALUE: string = "CONDITIONS_DE_PAIEMENTS";
    static CONDITIONS_DE_PAIEMENTS_DELETE_VALUE: string = "CONDITIONS_DE_PAIEMENTS";

}