
export class AuthoritiesContratFournisseur {
    static CONTRAT_FOURNISSEUR_LIST_VALUE: string = "CONTRAT_FOURNISSEUR";
    static CONTRAT_FOURNISSEUR_VALUE: string = "CONTRAT_FOURNISSEUR";
    static CONTRAT_FOURNISSEUR_ADD_VALUE: string = "CONTRAT_FOURNISSEUR";
    static CONTRAT_FOURNISSEUR_UPDATE_VALUE: string = "CONTRAT_FOURNISSEUR";
    static CONTRAT_FOURNISSEUR_DELETE_VALUE: string = "CONTRAT_FOURNISSEUR";
}